---
- debug: 
    msg: "In bpl, ansible-postgis, tasks/main.yml. postgresql_version is {{ postgresql_version }}, postgis_version is {{ postgis_version }}, and postgis_package_version is {{ postgis_package_version }}  "
    
# - name: Configure the PostgreSQL APT key
#   apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
#
# - name: Configure the PostgreSQL APT repositories
#   apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release}}-pgdg main"
#                   state=present
#   ignore_errors: True            

- name: Install PostGIS
  apt:
    name:
      - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}
    state: present
  ignore_errors: True
